steps:
  # 設定版本號和建置編號
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      # 獲取版本號和建置編號
      VERSION=${_VERSION:-$(python3 -c "from version import __version__; print(__version__)")}
      BUILD_NUM=${BUILD_ID:0:8}
      echo "Building STG version: $${VERSION}.$$BUILD_NUM"
      
      # 設定環境變數供後續步驟使用
      echo "VERSION=$${VERSION}" > /workspace/build_vars.env
      echo "BUILD_NUM=$$BUILD_NUM" >> /workspace/build_vars.env
      echo "IMAGE_TAG=$${VERSION}.$$BUILD_NUM-stg" >> /workspace/build_vars.env

  # 建置 Docker 映像 (使用版本標籤)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      source /workspace/build_vars.env
      docker build \
        --build-arg VERSION=$$VERSION \
        --build-arg BUILD_NUMBER=$$BUILD_NUM \
        -t gcr.io/$PROJECT_ID/japan-property-analyzer:latest \
        -t gcr.io/$PROJECT_ID/japan-property-analyzer:$$IMAGE_TAG \
        .

  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      source /workspace/build_vars.env
      docker push gcr.io/$PROJECT_ID/japan-property-analyzer:latest
      docker push gcr.io/$PROJECT_ID/japan-property-analyzer:$$IMAGE_TAG

  # 部署到 Cloud Run (STG 環境)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      source /workspace/build_vars.env
      
      # 獲取 OAuth 憑證
      GOOGLE_CLIENT_ID=$(gcloud secrets versions access latest --secret=google-oauth-client-id)
      GOOGLE_CLIENT_SECRET=$(gcloud secrets versions access latest --secret=google-oauth-client-secret)
      
      gcloud run deploy japan-property-analyzer \
        --image gcr.io/$PROJECT_ID/japan-property-analyzer:$$IMAGE_TAG \
        --region asia-northeast1 \
        --platform managed \
        --allow-unauthenticated \
        --set-env-vars GA_TRACKING_ID=G-59XMZ0SZ0G,ENVIRONMENT=staging,APP_VERSION=$$VERSION,BUILD_NUMBER=$$BUILD_NUM,NO_INDEX=true,SECRET_KEY=8ec8f8b4ba20148030b64d6a6cc5cccca92fce3fd2dc09c5ddeb6f6cd723a868,GOOGLE_CLIENT_ID=$$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$$GOOGLE_CLIENT_SECRET \
        --memory 1Gi \
        --cpu 1 \
        --max-instances 10 \
        --timeout 300 \
        --ingress all \
        --execution-environment gen2

# 設定觸發條件：當推送到非 main 分支時觸發
options:
  logging: CLOUD_LOGGING_ONLY 